/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AIChatbotAWSBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AIChatbotAWSDB": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "AIChatbotAWSVPC": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "AuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BedrockAccessKeyId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BedrockSecretAccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
